[build]
  publish = "public"

[[redirects]]
  from = "/"
  to = "/admin.html"
  status = 302

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/f/*"
  to = "/form.html"
  status = 200
